// Generated by scripts/gen-brand.mjs — do not edit; edit the generator.
export const MARK = `<img class="brand-mark" src="/assets/flower-mark-128.png" width="26" height="26" alt="" aria-hidden="true" decoding="async">`;
