#!/usr/bin/env node
/**
 * The NOSHASHI flower — one geometry, every vector brand file.
 *
 * The artwork is the owner's flower (brand/flower-source.png): four long
 * cardinal petals, four diagonals (the lower pair longer, as drawn), four
 * inner petals and a lit core. The app icon uses that artwork itself
 * (scripts/gen-brand-raster.mjs). Everything that must stay crisp at
 * 16-24px (favicon, site header, console marks, the menu-bar template)
 * uses this vector tracing of it, measured from the source image in its
 * own pixel space and normalised to a 100-unit box.
 *
 * Two renderings:
 *   color  translucent petals, lime edges and veins, a white-hot core:
 *          the source artwork's look.
 *   mono   one flat colour, petals separated by transparent cuts: for a
 *          macOS template image, currentColor chrome and print.
 *
 *   node scripts/gen-brand.mjs          write every file
 *   node scripts/gen-brand.mjs --check  fail if any file is stale (CI)
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const r = (n) => Math.round(n * 100) / 100;

// Measured in the source image: core at (628, 578); a 1210px square
// around it holds every petal tip. Map that square to 0..100.
const SRC = { cx: 628, cy: 578, box: 1210 };
const k = 100 / SRC.box;

/** A vesica petal, pointed at both ends, from the core to (dx, dy) source pixels, half-width hw source pixels. */
function petal(dx, dy, hw) {
  const len = Math.hypot(dx, dy);
  const ux = dx / len, uy = dy / len; // along the petal
  const nx = -uy, ny = ux; // across it
  const at = (along, across) =>
    `${r(50 + (ux * along + nx * across) * k)} ${r(50 + (uy * along + ny * across) * k)}`;
  return (
    `M${at(0, 0)}` +
    `C${at(len * 0.22, hw * 1.25)} ${at(len * 0.64, hw * 1.2)} ${at(len, 0)}` +
    `C${at(len * 0.64, -hw * 1.2)} ${at(len * 0.22, -hw * 1.25)} ${at(0, 0)}Z`
  );
}

export const FLOWER = {
  viewBox: "0 0 100 100",
  // Back to front.
  diagonal: [
    petal(-348, 397, 98), petal(350, 397, 98), // lower pair, longer
    petal(-285, -320, 86), petal(290, -320, 86), // upper pair
  ],
  cardinal: [petal(0, -549, 132), petal(0, 558, 122), petal(-582, 2, 112), petal(587, 2, 112)],
  inner: [petal(-120, -250, 56), petal(120, -250, 56), petal(-150, 330, 64), petal(150, 330, 64)],
  veins: [
    `M${r(50)} ${r(50 - 549 * k)}V${r(50 + 558 * k)}`,
    `M${r(50 - 582 * k)} ${r(50 + 2 * k)}H${r(50 + 587 * k)}`,
  ],
};

const ALL = () => [...FLOWER.diagonal, ...FLOWER.cardinal, ...FLOWER.inner];

/** The glowing rendering. `id` namespaces gradients per instance. */
export function flowerColor({ id = "nf" } = {}) {
  return (
    `<defs>` +
    `<radialGradient id="${id}-p" gradientUnits="userSpaceOnUse" cx="50" cy="50" r="50">` +
    `<stop offset="0" stop-color="#EAFFA0" stop-opacity=".95"/>` +
    `<stop offset=".14" stop-color="#8EDD4A" stop-opacity=".62"/>` +
    `<stop offset=".4" stop-color="#2A7F32" stop-opacity=".42"/>` +
    `<stop offset="1" stop-color="#0A3316" stop-opacity=".62"/>` +
    `</radialGradient>` +
    `<radialGradient id="${id}-c" gradientUnits="userSpaceOnUse" cx="50" cy="50" r="13">` +
    `<stop offset="0" stop-color="#fff"/>` +
    `<stop offset=".18" stop-color="#F4FFB8"/>` +
    `<stop offset=".5" stop-color="#A9F152" stop-opacity=".55"/>` +
    `<stop offset="1" stop-color="#7BD83A" stop-opacity="0"/>` +
    `</radialGradient>` +
    `</defs>` +
    `<g fill="url(#${id}-p)" stroke="#8FE34E" stroke-width=".55" stroke-linejoin="round">` +
    ALL().map((d) => `<path d="${d}"/>`).join("") +
    `</g>` +
    `<g stroke="#C6F77E" stroke-width=".35" stroke-opacity=".85">` +
    FLOWER.veins.map((d) => `<path d="${d}"/>`).join("") +
    `</g>` +
    `<circle cx="50" cy="50" r="13" fill="url(#${id}-c)"/>`
  );
}

/** The flat rendering: cardinals cut out of the diagonals, veins cut through. */
export function flowerMono({ id = "nm", fill = "currentColor" } = {}) {
  const gap = 2.4;
  return (
    `<mask id="${id}" maskUnits="userSpaceOnUse" x="0" y="0" width="100" height="100">` +
    FLOWER.diagonal.map((d) => `<path d="${d}" fill="#fff"/>`).join("") +
    FLOWER.cardinal
      .map((d) => `<path d="${d}" fill="#000" stroke="#000" stroke-width="${gap * 2}" stroke-linejoin="round"/><path d="${d}" fill="#fff"/>`)
      .join("") +
    FLOWER.veins.map((d) => `<path d="${d}" stroke="#000" stroke-width="1.6"/>`).join("") +
    `<circle cx="50" cy="50" r="6.5" fill="#fff"/>` +
    `</mask>` +
    `<rect width="100" height="100" fill="${fill}" mask="url(#${id})"/>`
  );
}

const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="none">
<!-- NOSHASHI flower. Generated by scripts/gen-brand.mjs; edit there. -->
${flowerColor({ id: "nf" })}
</svg>
`;

const mono = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="none">
<!-- NOSHASHI flower, single colour. Generated by scripts/gen-brand.mjs; edit there. -->
${flowerMono({ id: "nm", fill: "#000" })}
</svg>
`;

const GENERATED = "Generated by scripts/gen-brand.mjs — do not edit; edit the generator.";

const flowerTs = `// ${GENERATED}
export const FLOWER = ${JSON.stringify(FLOWER, null, 2)} as const;
`;

// The site header mark, in the artwork's own colours on both themes.
const brandMarkJs = `// ${GENERATED}
export const MARK = \`<svg viewBox="0 0 100 100" width="26" height="26" fill="none" aria-hidden="true">${flowerColor({ id: "hf" })}</svg>\`;
`;

const outputs = {
  "src/components/nova/brand/flower.ts": flowerTs,
  "api/_lib/brand-mark.js": brandMarkJs,
  "site/favicon.svg": favicon,
  "public/app-icon.svg": favicon,
  "brand/flower-mono.svg": mono,
};

const check = process.argv.includes("--check");
let stale = 0;
for (const [rel, body] of Object.entries(outputs)) {
  const path = resolve(root, rel);
  if (check) {
    let current = "";
    try { current = readFileSync(path, "utf8"); } catch {}
    if (current !== body) { console.error(`stale: ${rel} — run node scripts/gen-brand.mjs`); stale += 1; }
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, body);
    console.log(`wrote ${rel}`);
  }
}
if (stale) process.exit(1);
