-- Baseline of the `noshashi` schema.
--
-- These nine tables, their policies, functions and triggers were created
-- directly against the hosted database and existed only there. The two earlier
-- migrations in this directory carry grants and assume all of it already
-- exists, so a clean database could not be rebuilt from this repository at all.
-- For a product whose claim is that its output is auditable, a schema nobody
-- can review or reproduce is the wrong thing to leave undocumented.
--
-- This file was generated by introspecting the live database on 2026-09-10 and
-- then rewritten by hand: constraints are inlined into their tables rather than
-- appended, and the indexes Postgres creates implicitly for primary keys and
-- unique constraints are omitted. It is therefore a faithful record of what is
-- deployed, not a byte-for-byte pg_dump. Before trusting it for disaster
-- recovery, restore it into an empty project and diff against production —
-- `supabase db diff` will tell you if anything here drifted.
--
-- Written to be re-runnable: every statement either guards with IF NOT EXISTS
-- or drops first, so applying it to the database it came from is a no-op.

create schema if not exists noshashi;

-- ── Tables ──────────────────────────────────────────────────────────────────

-- One row per authenticated user. `id` is the auth.users id rather than a key
-- of its own, so every policy below can compare against auth.uid() directly and
-- deleting the user cascades the whole account away.
create table if not exists noshashi.accounts (
  id            uuid primary key references auth.users(id) on delete cascade,
  email         text        not null,
  display_name  text,
  organization  text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists noshashi.alerts (
  id               uuid        primary key default gen_random_uuid(),
  account_id       uuid        not null references noshashi.accounts(id) on delete cascade,
  kind             text        not null check (kind in ('policy_drift', 'credential_expiry', 'domain_governance', 'reserve')),
  severity         text        not null default 'info' check (severity in ('info', 'warn', 'critical')),
  title            text        not null,
  body             text,
  subject_address  text,
  domain_code      text,
  acknowledged_at  timestamptz,
  created_at       timestamptz not null default now()
);

-- Only the hash is stored. The key itself is shown once at creation and is
-- unrecoverable afterwards, which is the point: a leaked database yields no
-- usable credentials.
create table if not exists noshashi.api_keys (
  id            uuid        primary key default gen_random_uuid(),
  account_id    uuid        not null references noshashi.accounts(id) on delete cascade,
  name          text        not null,
  prefix        text        not null,
  key_hash      text        not null unique,
  last_used_at  timestamptz,
  revoked_at    timestamptz,
  created_at    timestamptz not null default now()
);

-- Keyed by account rather than carrying its own id: an account has exactly one
-- entitlement row, and the primary key is what enforces that.
create table if not exists noshashi.entitlements (
  account_id          uuid        primary key references noshashi.accounts(id) on delete cascade,
  tier                text        not null default 'operator' check (tier in ('operator', 'desk', 'institution')),
  seats               integer     not null default 1,
  features            text[]      not null default '{}'::text[],
  verification_quota  integer     not null default 0,
  valid_until         timestamptz,
  updated_at          timestamptz not null default now()
);

create table if not exists noshashi.portfolios (
  id          uuid        primary key default gen_random_uuid(),
  account_id  uuid        not null references noshashi.accounts(id) on delete cascade,
  name        text        not null,
  created_at  timestamptz not null default now()
);

create table if not exists noshashi.portfolio_wallets (
  id            uuid        primary key default gen_random_uuid(),
  portfolio_id  uuid        not null references noshashi.portfolios(id) on delete cascade,
  address       text        not null,
  label         text,
  created_at    timestamptz not null default now(),
  unique (portfolio_id, address)
);

-- `digest` is unique because a receipt is identified by its canonical hash. Two
-- rows with one digest would mean the same adjudication was recorded twice and
-- an auditor could not tell which is authoritative.
create table if not exists noshashi.receipts (
  id                uuid          primary key default gen_random_uuid(),
  account_id        uuid          not null references noshashi.accounts(id) on delete cascade,
  digest            text          not null unique,
  verdict           text          not null check (verdict in ('go', 'hold', 'no-go')),
  domain_code       text          not null,
  subject_address   text,
  amount_xrp        numeric(20,6),
  anchored_tx_hash  text,
  anchored_ledger   integer,
  created_at        timestamptz   not null default now()
);

create table if not exists noshashi.subscriptions (
  id                      uuid        primary key default gen_random_uuid(),
  account_id              uuid        not null references noshashi.accounts(id) on delete cascade,
  stripe_customer_id      text,
  stripe_subscription_id  text        unique,
  price_id                text,
  tier                    text        not null default 'operator' check (tier in ('operator', 'desk', 'institution')),
  status                  text        not null default 'incomplete',
  seats                   integer     not null default 1 check (seats > 0),
  current_period_end      timestamptz,
  cancel_at_period_end    boolean     not null default false,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

-- api_key_id is ON DELETE SET NULL, not CASCADE: revoking a key must not erase
-- the record of what it was used to verify. The billing history outlives the
-- credential.
create table if not exists noshashi.verification_events (
  id               bigserial     primary key,
  account_id       uuid          not null references noshashi.accounts(id) on delete cascade,
  api_key_id       uuid          references noshashi.api_keys(id) on delete set null,
  domain_code      text          not null,
  verdict          text          not null check (verdict in ('go', 'hold', 'no-go')),
  receipt_digest   text          not null,
  subject_address  text,
  amount_xrp       numeric(20,6),
  latency_ms       integer,
  billed           boolean       not null default false,
  created_at       timestamptz   not null default now(),
  subject          text
);

-- ── Functions ───────────────────────────────────────────────────────────────

create or replace function noshashi.touch_updated_at()
returns trigger
language plpgsql
set search_path to ''
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

-- Runs as the definer on insert into auth.users, because the signing-up user
-- does not yet have an account row and so could not insert one under RLS.
create or replace function noshashi.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  insert into noshashi.accounts (id, email, display_name)
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(new.raw_user_meta_data ->> 'display_name', '')
  )
  on conflict (id) do nothing;

  insert into noshashi.entitlements (account_id, tier, seats, features, verification_quota)
  values (new.id, 'operator', 1, array['console','gate','agent','export'], 0)
  on conflict (account_id) do nothing;

  return new;
end;
$function$;

-- Decrement and test in one statement so two concurrent verifications cannot
-- both observe the last credit and both spend it.
create or replace function noshashi.consume_verification_credit(p_account uuid)
returns boolean
language plpgsql
security definer
set search_path to 'noshashi', 'public'
as $function$
declare
  v_quota integer;
begin
  update noshashi.entitlements
  set verification_quota = verification_quota - 1
  where account_id = p_account
    and verification_quota >= 1
  returning verification_quota into v_quota;

  -- found is true exactly when an eligible row was updated: a missing row
  -- or a zero balance both read as "no credit available".
  return found;
end;
$function$;

-- ── Triggers ────────────────────────────────────────────────────────────────

drop trigger if exists accounts_touch on noshashi.accounts;
create trigger accounts_touch
  before update on noshashi.accounts
  for each row execute function noshashi.touch_updated_at();

drop trigger if exists entitlements_touch on noshashi.entitlements;
create trigger entitlements_touch
  before update on noshashi.entitlements
  for each row execute function noshashi.touch_updated_at();

drop trigger if exists subscriptions_touch on noshashi.subscriptions;
create trigger subscriptions_touch
  before update on noshashi.subscriptions
  for each row execute function noshashi.touch_updated_at();

-- Without this, a user can authenticate but has no account or entitlement row,
-- so every screen behind the paywall renders empty for a valid session.
drop trigger if exists on_auth_user_created_noshashi on auth.users;
create trigger on_auth_user_created_noshashi
  after insert on auth.users
  for each row execute function noshashi.handle_new_user();

-- ── Indexes ─────────────────────────────────────────────────────────────────
-- Primary key and unique indexes are created implicitly by the constraints
-- above and are deliberately not repeated here.

create index if not exists alerts_account_time_idx
  on noshashi.alerts using btree (account_id, created_at desc);

create index if not exists api_keys_account_idx
  on noshashi.api_keys using btree (account_id);

create index if not exists portfolios_account_idx
  on noshashi.portfolios using btree (account_id);

create index if not exists receipts_account_time_idx
  on noshashi.receipts using btree (account_id, created_at desc);

create index if not exists subscriptions_account_idx
  on noshashi.subscriptions using btree (account_id);

create index if not exists verification_events_account_time_idx
  on noshashi.verification_events using btree (account_id, created_at desc);

-- Partial: billing only ever sweeps unbilled rows, and the index stays small
-- because billed rows leave it.
create index if not exists verification_events_unbilled_idx
  on noshashi.verification_events using btree (account_id) where (billed = false);

-- ── Row level security ──────────────────────────────────────────────────────

alter table noshashi.accounts            enable row level security;
alter table noshashi.alerts              enable row level security;
alter table noshashi.api_keys            enable row level security;
alter table noshashi.entitlements        enable row level security;
alter table noshashi.portfolio_wallets   enable row level security;
alter table noshashi.portfolios          enable row level security;
alter table noshashi.receipts            enable row level security;
alter table noshashi.subscriptions       enable row level security;
alter table noshashi.verification_events enable row level security;

-- Every policy wraps auth.uid() as `(select auth.uid())`. That is not style:
-- the bare call is volatile and Postgres re-evaluates it once per row, while
-- the scalar subquery is evaluated once for the whole statement.
--
-- Note what has no policy. entitlements, subscriptions and verification_events
-- are SELECT-only to their owner — they are written by Edge Functions holding
-- the service role, so a user cannot grant themselves a tier or mark their own
-- usage as billed.

drop policy if exists accounts_select_own on noshashi.accounts;
create policy accounts_select_own on noshashi.accounts
  for select to authenticated
  using ((select auth.uid()) = id);

drop policy if exists accounts_update_own on noshashi.accounts;
create policy accounts_update_own on noshashi.accounts
  for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists alerts_select_own on noshashi.alerts;
create policy alerts_select_own on noshashi.alerts
  for select to authenticated
  using ((select auth.uid()) = account_id);

drop policy if exists alerts_update_own on noshashi.alerts;
create policy alerts_update_own on noshashi.alerts
  for update to authenticated
  using ((select auth.uid()) = account_id)
  with check ((select auth.uid()) = account_id);

drop policy if exists api_keys_select_own on noshashi.api_keys;
create policy api_keys_select_own on noshashi.api_keys
  for select to authenticated
  using ((select auth.uid()) = account_id);

drop policy if exists api_keys_insert_own on noshashi.api_keys;
create policy api_keys_insert_own on noshashi.api_keys
  for insert to authenticated
  with check ((select auth.uid()) = account_id);

drop policy if exists api_keys_update_own on noshashi.api_keys;
create policy api_keys_update_own on noshashi.api_keys
  for update to authenticated
  using ((select auth.uid()) = account_id)
  with check ((select auth.uid()) = account_id);

drop policy if exists entitlements_select_own on noshashi.entitlements;
create policy entitlements_select_own on noshashi.entitlements
  for select to authenticated
  using ((select auth.uid()) = account_id);

drop policy if exists portfolios_all_own on noshashi.portfolios;
create policy portfolios_all_own on noshashi.portfolios
  for all to authenticated
  using ((select auth.uid()) = account_id)
  with check ((select auth.uid()) = account_id);

-- Reached through its portfolio: a wallet has no account_id of its own, so
-- ownership is proved by the parent row.
drop policy if exists portfolio_wallets_all_own on noshashi.portfolio_wallets;
create policy portfolio_wallets_all_own on noshashi.portfolio_wallets
  for all to authenticated
  using (exists (
    select 1 from noshashi.portfolios p
    where p.id = portfolio_wallets.portfolio_id
      and p.account_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from noshashi.portfolios p
    where p.id = portfolio_wallets.portfolio_id
      and p.account_id = (select auth.uid())
  ));

drop policy if exists receipts_select_own on noshashi.receipts;
create policy receipts_select_own on noshashi.receipts
  for select to authenticated
  using ((select auth.uid()) = account_id);

drop policy if exists receipts_insert_own on noshashi.receipts;
create policy receipts_insert_own on noshashi.receipts
  for insert to authenticated
  with check ((select auth.uid()) = account_id);

drop policy if exists subscriptions_select_own on noshashi.subscriptions;
create policy subscriptions_select_own on noshashi.subscriptions
  for select to authenticated
  using ((select auth.uid()) = account_id);

drop policy if exists verification_events_select_own on noshashi.verification_events;
create policy verification_events_select_own on noshashi.verification_events
  for select to authenticated
  using ((select auth.uid()) = account_id);

-- ── Grants ──────────────────────────────────────────────────────────────────
-- `anon` is granted nothing, deliberately. An unauthenticated caller cannot so
-- much as see that this schema exists, and 20260828_harden_function_grants
-- depends on that remaining true.

grant usage on schema noshashi to authenticated, service_role;

grant select                         on noshashi.accounts            to authenticated;
grant select, update                 on noshashi.alerts              to authenticated;
grant insert                         on noshashi.alerts              to authenticated;
grant select, insert, update         on noshashi.api_keys            to authenticated;
grant select                         on noshashi.entitlements        to authenticated;
grant select, insert, update, delete on noshashi.portfolios          to authenticated;
grant select, insert, update, delete on noshashi.portfolio_wallets   to authenticated;
grant select, insert, update         on noshashi.receipts            to authenticated;
grant select                         on noshashi.subscriptions       to authenticated;
grant select                         on noshashi.verification_events to authenticated;

grant all on all tables    in schema noshashi to service_role;
grant all on all sequences in schema noshashi to service_role;
